---
title: "Initial CV Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r basics, echo=FALSE}
library(targets)
library(DT)
```

```{r git_check, echo=FALSE}
{
s = function(cmd) suppressWarnings(system(cmd,
    intern = TRUE, ignore.stderr = TRUE))
commit = substr(s('git rev-parse HEAD'), 1, 8)
uncommitted = ''
if (!length(commit))
   commit = 'unknown'
else if(length(s('git diff-index HEAD --'))>0)
   uncommitted = 'with uncommitted changes'
}
```

Git commit: `r commit` `r uncommitted`

Rendered: `r Sys.time()`

Workflow definition:

```{r echo = F}
DT::datatable(t(as.data.frame(as.list(Wf))),
              fillContainer = FALSE,
              autoHideNavigation = TRUE,
              options = list(pageLength = 50))
```

In the below, time differences are in minutes.

```{r echo = F}
DT::datatable(pretty.table.numbers(tar_read(cv.summary)),
              rownames = FALSE,
              fillContainer = FALSE,
              autoHideNavigation = TRUE,
              options = list(pageLength = 50,
                             autoWidth = TRUE))
```
