---
title: "Plot predicted AOD at 470nm"
author: "Yang Liu"
date: "8/7/2019"
output:
  html_document:
    toc: true
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, message=FALSE, warning=FALSE,
                      error = F, fig.width = 7, fig.height = 4.5)
```

```{r}
source("~/liuyanguu/CWV/Code/cwv_funcs.R")

aod20_data_global <- read.fst("/data-coco/ECHO_PM/AeronetAODV3Level2/AOD_Level20_All_Points_V3_global.fst", as.data.table = T)

#' prepare aer_date for interpolation of AOD470nm 
#' 
prepare_for_interpolation <- function(aod20_data_global){
  aod20_data_global <- aod20_data_global[, -c("AOD_1020nm", "AOD_1640nm"), with = F]
  aod20_data_global[,obs:=.I]
  setkey(aod20_data_global, obs)
  vars_aod_sub <- grep("AOD_", names(aod20_data_global), value = T)
  aod20_data_global$N_NAAOD <- rowSums(!is.na(aod20_data_global[,..vars_aod_sub]))
  return(aod20_data_global)
}

aod20_data_global <- prepare_for_interpolation(aod20_data_global)

```

get one side observations

```{r}
vars_wv <- grep("Exact_Wavelengths_of_AOD", names(aod20_data_global), value = T)
vars_aod_sub <- grep("AOD_", names(aod20_data_global), value = T)

d <- melt(aod20_data_global[, c(vars_aod_sub,vars_wv[1:22], "obs"), with = F], measure = list(vars_aod_sub, vars_wv[1:22]),value.name = c("aod", "exact_wv"))
# choose non-NA and >0 AOD
d <- d[!is.na(aod)]
# d[, variable := readr::parse_number(levels(variable))[as.integer(variable)]]
# should have points on both sides, otherwise pick out the id
obs_os <- d[, by = obs, .(oneside = (max(exact_wv)-0.47)*(min(exact_wv)-0.47)>0)][oneside ==T, obs]

```

# 1. Have points on both sides of 470 nm

```{r}
# to make some plots to see the fitting results 
test <- aod20_data_global[, c("obs","N_NAAOD", vars_aod_sub), with = F][!obs%in%obs_os]
table(test[,N_NAAOD])

make.test.plot.points <- function(available_points){
  print(paste0(available_points, " available points for prediction:\n"))
  test0 <- test[N_NAAOD==available_points]
  make.test.fit.plot <- function(i){
    t1 <-  test0[i,c(vars_aod_sub), with = F]
    df1 <- na.omit(melt(t1, measure.vars = c(vars_aod_sub), variable.name = "aod"))
    df1[,x:=readr::parse_number(as.character(aod))/1000]
    # refit to the dataset to recover the fitted line 
    fit0 <- lm(data = df1, log(value) ~  log(x) + I((log(x))^2))
    x <- seq(from = range(c(df1$x,0.47))[1], to = range(c(df1$x,0.47))[2], length.out = 100)
    yhat <- exp(predict(fit0, newdata = as.data.frame(x)))
    p1 = ggplot(data = data.frame(x, yhat), aes(x = x, y = yhat)) + 
      geom_line() + geom_point(data = df1, aes(x=x, y = value)) + 
      geom_point(data = data.frame(x = 0.47, y = exp(predict(fit0, newdata = data.frame(x = 0.47)))), aes(x=x, y=y), color = "red", size = 2) + theme_classic()
    p1
  }
  set.seed(1234)
  # 
  test_fig_list <- lapply(sample(nrow(test0), min(12,nrow(test0))), make.test.fit.plot)
  gridExtra::grid.arrange(grobs = test_fig_list, ncol = 4)
  # ggsave(gridExtra::grid.arrange(grobs = test_fig_list, ncol = 4), file = paste0( "figure/190806_fitted_pred470_os_n",available_points,".png"), width = 12, height = ceiling(nrow(test0)/4)*3)
}

invisible(lapply(2:7, make.test.plot.points))

```

# 2. Points on only one side of 470 nm

```{r}
test <- aod20_data_global[, c("obs","N_NAAOD", vars_aod_sub), with = F][obs%in%obs_os]
table(test[,N_NAAOD])

invisible(lapply(2:7, make.test.plot.points))


```

# 3. Points on only one side of 470 nm and no nearby points

```{r, echo = TRUE}
test <- aod20_data_global[obs%in%obs_os &is.na(AOD_440nm)&is.na(AOD_443nm)&is.na(AOD_490nm) &is.na(AOD_500nm),]

table(test[,N_NAAOD])

invisible(lapply(2:6, make.test.plot.points))

```

