---
title: "Drake Plan"
author: "Johnathan Rush, Yang Liu"
date: "08/14/2019"
output:
  html_document:
    toc: true
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = T, message=FALSE, warning=FALSE)
```

# Write the plan

```{r}
# See `drake_funcs.R` for functions used in this drake plan #

# beginning of script where we will have a plan to:
# select Aeronet in CONUS
# select Aeronet in NEMIA
# calculate nearest idLSTpair0's. May need shortcut that uses buffer around stations to reduce possibility set. 

# select from the daily data the subsets above (one of the two)
# calc columns as in old script
# as.numeric columns as necessary
# remove rows without AOD? probably not - they may have CWV
# ? which other columns to we want?
# restrict to 2000+ (parameter so that different subsets could be taken later)

# Libraries
# if needed, update drake
if(packageVersion("drake") < "7.4") install.packages("drake")
if(packageVersion("SHAPforxgboost") < "0.0.2") devtools::install_github("liuyanguu/SHAPforxgboost")

suppressPackageStartupMessages({
  library(sf)
  library(magrittr)
  library(drake)
  library(data.table)
  library(fst)
  library(future)
  library(here)
  library(nngeo)
  library(ggplot2)
  library(SHAPforxgboost)
})
# ** need to revise accordingly the path to your local clone of Just_universal **
source(here("../Just_universal/code/xgboost_cvtune.R"))
source(here("../Just_universal/code/xgboost_cv_RFE.R"))

# Parameters ####
# the aer site info. file:
aer_stn_path = "/data-coco/ECHO_PM/AeronetAODV3Level2/AOD/AOD20/aeronet_locations_v3.txt"
# aer_data_path = '~/qnap_geo/aeronet/All_Sites_Times_All_Points_AOD20_20180603.dat'
# aer_data_path = '/scratch/temp/All_Sites_Times_All_Points_AOD20_20180603.dat' 
# the aer data files:
aer_files_path = "/data-coco/ECHO_PM/AeronetAODV3Level2/AOD/AOD20/ALL_POINTS/"
date_start = "2018-01-01" # do not include in sel_data_bytime if don't want to limit
date_end   = "2018-12-31" # do not include in sel_data_bytime if don't want to limit
sats = c("terra", "aqua")

# MCD19 data load and save output: 
mcd19path = "/data-coco/mcd19/fst/nemia/2018/" # now there is only 2018 data 
mcd19path_CONUS = "/data-coco/mcd19/fst/conus/2018/"
MCD19_T_files <- list.files(path = mcd19path_CONUS, pattern = "T", full.names = T)
MCD19_A_files <- list.files(path = mcd19path_CONUS, pattern = "A", full.names = T)
out_dir = "/data-coco/mcd19/fst/conus/2018_AOD_newVar/"
# how many MCD days (files) to work on:
MCD_files_i = c(1:length(MCD19_T_files))

# for reporting purpose
y_var = "diff_AOD"
y_var_pred = "diff_AOD_pred"
# how many features to print in scatterplots
n_vars = 10

# point to cache: 
ssd_cache = drake_cache(path = "/scratch/cache/aeronet_drake")
set.seed(1234)
```

# Plan part 1

```{r}
# CONUS Drake Plans  ------------------------------------------------------------
source(here("R/drake_funcs.R"))
conus_plan <- drake_plan(
  # 1.  Aeroent ---------------------------------------------------------------------
  
  # AERONET station locations file: 
  aer_stns = fread(file = file_in(aer_stn_path), col.names = c("Site_Name", "lon", "lat", "elevm")),
  conus_buff = get_conus_buff(),
  nemia_buff = get_nemia_buff(),
  aerpts = get_aer_spatial(aer_stns),               # wgs84
  conus_aer = select_points(aerpts, conus_buff),    # AERONET sites in CONUS as points
  nemia_aer = select_points(conus_aer, nemia_buff), # AERONET sites in NEMIA as points
  
  # get nearest MODIS cells 
  refgrid = get_ref_grid(),

  # aeronet sites with cloest MODIS grid
  aer_nearest = get_nearest_cell(conus_aer, refgrid), # Aeronet matched to grid, 174x4
  aer_nearest_2 = remove_site_on_water(aer_nearest), # remove 2 sites on water
  
  # limit aeronet data by date (aer_btw)
  aer_data = get_stn_data(aod_dir = file_in(aer_files_path)),  # 26171206x56, 11G
  aer_btw = target(sel_data_bytime(aer_data, date_start, date_end),
                   transform = map(date_start = !!date_start, 
                                   date_end = !!date_end,
                                   .id = FALSE)),
  # limit aeronet data by station, could be NEMIA or CONUS 
  sel_aer_region = target(sel_data_bystation(aer_btw, aer_nearest_2),
                      transform = map(aer_btw, .id = FALSE)),
  
  
  # 2. Interpolation -----------------------------------------------------------
  # so instead of running all the Aeronet data, only run what is used
  # it also join with the nearest grid id 
  wPred = target(interpolate_aod(sel_aer_region, aer_nearest_2), transform = map(sel_aer_region, .id = FALSE)),
  
  # 3. WPred Join MCD19 -----------------------------------------------------------
  # mcd is the large MCD19 dataset, limit to `refsub`:nearby(300km) when readin to 
  # control total lines, unable to read in all data together, too many rows
  mcd = target(read_mcd19_one(i, sat = sat, file_in(mcd19path_CONUS)), 
               transform = cross( i = !!MCD_files_i, 
                                  sat = !!sats),
               format = "fst"),
  # join is the rolling-joined dataset with aeronet
  join = target(rolling_join(mcd_sat = mcd, aer_data_wPred = wPred),
                transform = cross(mcd, wPred, .id = mcd)),
  
  # For calculating new variables
  # selected aeronet 
  sel_aer = target(get_conus_aer_used(conus_aer, sel_aer_region),
                  transform = map(sel_aer_region, .id = FALSE)),
  
  # buffers 
  ref = target(ref_in_buffer(sel_aer, refgrid),
             transform = map(sel_aer)),
  # sites
  p = target(get_site_list(sel_aer), transform = map(sel_aer)),
  n = target(get_site_name(sel_aer), transform = map(sel_aer)),
 
  # mapping 
  # this way doesn't work:
  # sub_grid = target(select_refgrid_subset(ref_list0 = ref, point0 = p, name0 = n),
  #              transform = map(ref, p, n))
  sub_grid = target(purrr_pmap(ref = ref, p = p, n = n),
               transform = map(ref, p, n, .id = FALSE),
               format = "fst"),
  # calculate new vars to obtain the dataset ready for modeling for terra and aqua, using join, mcd, sub_grid 
  new_var = target(aod_MODIS_newVars(aod_join_MODIS = join, 
                                 MODIS_all = mcd, refDT_sub = sub_grid),
               transform = map(join, mcd, .id = c(join)),
               format = "fst"),
  # deliver two rowbinded dataset: for terra and aqua 
  # I am not sure what this way doesn't work: 
  # binded = target(rbindlist(new_var),
  #                 transform = combine(new_var, .by = c(i, sat))),
  # `.id_chr` let you save the file using target names:
  out = target(write_new_var(new_var, id = .id_chr), transform = map(new_var))
)

conus_plan
nrow(conus_plan)
#drake_plan_source(conus_plan)
if(nrow(conus_plan)<100){
nemia_config <- drake_config(conus_plan, cache = ssd_cache) # show the dependency
# vis_drake_graph(nemia_config, from = names(nemia_config$layout))
vis_drake_graph(nemia_config, ncol_legend = 0)
}
```

# Plan part 2

```{r}
source(here("R/drake_funcs.R"))
# drake plan to run cv and output results 
conus_plan_cv <- drake_plan(
  # 5. CV -----------------------------------------------------------
  new_var = target(read_new_var(sat), transform = map(sat = !!sats)),
  new_dt = target(prepare_dt(new_var), transform = map(new_var, .id = FALSE)),
  cv_results = target(run_cv(dt = new_dt), transform = map(new_dt, .id = sat)),

  # 6. Report -----------------------------------------------------------
  print1 = target(report_rmse(cv_results),
                  transform = map(cv_results,.id = FALSE)),
  plot1 = target(plot_rmse(cv_results),
                 transform = map(cv_results,.id = FALSE)),
  # figures
  plotAOD = target(plot_AOD(cv_results),
                 transform = map(cv_results,.id = FALSE)),
  plotscatter = target(plot_scatter(cv_results),
                 transform = map(cv_results,.id = FALSE)),

  shap_long = target(get_SHAP_long(cv_results),
                  transform = map(cv_results,.id = FALSE)),
  plotSHAP1 = target(plot_SHAP(shap_long),
                 transform = map(shap_long,.id = FALSE)),
  plotSHAP2 = target(plot_SHAP_scatter(cv_results, shap_long),
                 transform = map(cv_results, shap_long,.id = FALSE)),
  report = rmarkdown::render(
    knitr_in("AOD_CONUS_Report.Rmd"),
    output_file = file_out("AOD_CONUS_Report.html"),
    output_format = rmarkdown::html_document(toc = TRUE))
)
nemia_config <- drake_config(conus_plan_cv, cache = ssd_cache) # show the dependency
# vis_drake_graph(nemia_config, from = names(nemia_config$layout))
vis_drake_graph(nemia_config)
```

# Run the two plans

```{r, eval = F}
# make(conus_plan, cache = ssd_cache)
time0 <- Sys.time()
future::plan(future::multiprocess)
options(future.globals.maxSize= 100*1024^3) 
make(conus_plan, cache = ssd_cache,
     parallelism = "future", jobs = 20)
Sys.time() - time0

# Allowing `add_hist` in `plot_scatter` (or use plotly) requires set lock_envir to FALSE:
make(conus_plan_cv, cache = ssd_cache, lock_envir = FALSE)
```
