---
title: "Drake Plan"
author: "Johnathan Rush, Yang Liu"
date: "08/14/2019"
output:
  html_document:
    toc: true
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = T, message=FALSE, warning=FALSE)
```

# Write the plan

```{r}
# See `drake_funcs.R` for functions used in drake plan #

# beginning of script where we will have a plan to:
# select Aeronet in CONUS
# select Aeronet in NEMIA
# calculate nearest idLSTpair0's. May need shortcut that uses buffer around stations to reduce possibility set. 

# select from the daily data the subsets above (one of the two)
# calc columns as in old script
# as.numeric columns as necessary
# remove rows without AOD? probably not - they may have CWV
# ? which other columns to we want?
# restrict to 2000+ (parameter so that different subsets could be taken later)

# Libraries
suppressPackageStartupMessages({
  library(sf)
  library(magrittr)
  library(drake)
  library(data.table)
  library(fst)
  library(future)
  library(here)
  library(nngeo)
  library(ggplot2)
  library(SHAPforxgboost)
})
# ** need to revise accordingly the path to your local Just_universal
source(here("../Just_universal/code/xgboost_cvtune.R"))
source(here("../Just_universal/code/xgboost_cv_RFE.R"))

# Parameters ####

aer_stn_path = "/data-coco/ECHO_PM/AeronetAODV3Level2/AOD/AOD20/aeronet_locations_v3.txt"

aer_data_path = '~/qnap_geo/aeronet/All_Sites_Times_All_Points_AOD20_20180603.dat'
aer_data_path = '/scratch/temp/All_Sites_Times_All_Points_AOD20_20180603.dat' # don't have time to play with Ethernet all day
# the aer data with AOD470nm
aer_data_path_new = "~/Intermediate/AOD_data/190628_aod20_wPred_NEMIA_idLST.fst"
  
aer_files_path = "/data-coco/ECHO_PM/AeronetAODV3Level2/AOD/AOD20/ALL_POINTS/"
date_start = "2018-01-01" # do not include in sel_data_bytime if don't want to limit
date_end   = "2018-12-31" # do not include in sel_data_bytime if don't want to limit
geo_region = "NEMIA"
sats = c("terra", "aqua")
# MCD19 data: 
mcd19path = "/data-coco/mcd19/fst/nemia/2018/" # now there is only 2018 data 
mcd19path_CONUS = "/data-coco/mcd19/fst/conus/2018/"
# point to cache: 
ssd_cache = new_cache(path = "/scratch/cache/aeronet_drake") 

# for reporting purpose
y_var = "diff_AOD"
y_var_pred = "diff_AOD_pred"


# Drake Plans  ------------------------------------------------------------

# load functions for drake: 
source(here("R/drake_funcs.R"))
# new plan Yang Liu
nemia_plan <- drake_plan(
  # 1.  Aeroent ---------------------------------------------------------------------
  
  # AERONET station locations file: 
  aer_stns = fread(file = file_in(aer_stn_path), col.names = c("Site_Name", "lon", "lat", "elevm")),
  conus_buff = get_conus_buff(),
  nemia_buff = get_nemia_buff(),
  aerpts = get_aer_spatial(aer_stns),               # wgs84
  conus_aer = select_points(aerpts, conus_buff),    # AERONET sites in CONUS as points
  nemia_aer = select_points(conus_aer, nemia_buff), # AERONET sites in NEMIA as points
  
  # get nearest MODIS cells 
  refgrid = get_ref_grid(),
  aer_nearest = get_nearest_cell(nemia_aer, refgrid), # Aeronet matched to grid, 174x4
  aer_nearest_NEMIA = remove_site_on_water(aer_nearest), # remove 2 sites 
  
  # limit aer sites by date (aer_btw)
  aer_data = get_stn_data(aod_dir = file_in(aer_files_path)),  # 26171206x56, 11G
  aer_btw = target(sel_data_bytime(aer_data, date_start, date_end),
                   transform = map(date_start = !!date_start, 
                                   date_end = !!date_end,
                                   .id = FALSE)),
  # limit by site 
  nemia = target(sel_data_bystation(aer_btw, aer_nearest_NEMIA),
                      transform = map(aer_btw), .id = FALSE),
  
  # 2. Interpolation -----------------------------------------------------------
  # so instead of running all the Aeronet data, only run what is used
  # it also join with the nearest grid id 
  wPred = target(interpolate_aod(nemia, aer_nearest_NEMIA), transform = map(nemia)),
  
  # 3. WPred Join MCD19 -----------------------------------------------------------
  # mcd is the large MCD19 dataset 
  # `mcd19path` could be revised to CONUS later 
  mcd = target(read_mcd19(sat, file_in(mcd19path)), transform = map(sat = c("terra", "aqua"))),
  # join is the rolling-joined dataset with aeronet
  join = target(rolling_join(mcd_sat = mcd, aer_data_wPred = wPred),
                transform = cross(mcd, wPred, .id = mcd)),
  
  
  sel_aer = target(aer_in_mcd19(aer_nearest_NEMIA, mcd19 = join),
             transform = map(join)),
  # buffers 
  ref = target(ref_in_buffer(nemia_aer_m = sel_aer, refgrid),
             transform = map(sel_aer)),
  # sites
  p = target(get_site_list(nemia_aer_m = sel_aer), transform = map(sel_aer)),
  n = target(get_site_name(nemia_aer_m = sel_aer), transform = map(sel_aer)),
 
  # mapping 
  # this way doesn't work:
  # sub = target(select_refgrid_subset(ref_list0 = ref, point0 = p, name0 = n),
  #              transform = map(ref, p, n))
  sub_grid = target(purrr_pmap(ref = ref, p = p, n = n),
               transform = map(ref, p, n, .id = FALSE)),
  # calculate new vars: the dataset ready for modeling 
  # for terra and aqua, using join, mcd, sub 
  new_var = target(aod_MODIS_newVars(aod_join_MODIS = join, 
                                 MODIS_all = mcd, refDT_sub = sub_grid),
               transform = map(join, mcd, sub_grid, .id = c(join))),
  
  # 5. CV -----------------------------------------------------------
  cv_results = target(run_cv(dt = new_var),transform = map(new_var)),
  
  # 6. MD -----------------------------------------------------------
  print1 = target(report_rmse(cv_results),
                  transform = map(cv_results,.id = FALSE)),
  plot1 = target(plot_rmse(cv_results),
                 transform = map(cv_results,.id = FALSE)),
  plotSHAP1 = target(plot_SHAP(cv_results),
                 transform = map(cv_results,.id = FALSE)),
  report = rmarkdown::render(
    knitr_in("report.Rmd"),
    output_file = file_out("report.html"))
)
nemia_plan
#drake_plan_source(nemia_plan)
nemia_config <- drake_config(nemia_plan, cache = ssd_cache) # show the dependency
# vis_drake_graph(nemia_config, from = names(nemia_config$layout))
vis_drake_graph(nemia_config, ncol_legend = 0)

```

# Run the plan 

```{r, eval = F}

future::plan(future::multiprocess)
options(future.globals.maxSize= 100*1024^3) 
make(nemia_plan, cache = ssd_cache,
     parallelism = "future", jobs = 20)

## Some simple analysis 
loadd("new_var_join_mcd_terra", cache = ssd_cache)
loadd("new_var_join_mcd_aqua", cache = ssd_cache)
SHAPforxgboost::scatter.plot.diagonal(new_var_join_mcd_aqua, "Optical_Depth_047",
                                      "Mean_AOD270km")
cor(as.matrix(new_var_join_mcd_terra[,c(grep("Mean_AOD", names(new_var_join_mcd_terra), value = T), "AOD_470nm"), with = F]))
## 
loadd(cache = ssd_cache) # load all object 

# to see the updated graph, run config again
nemia_config <- drake_config(nemia_plan, cache = ssd_cache) # show the dependency
vis_drake_graph(nemia_config)

```
