---
title: "Initial CV Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r basics, echo=FALSE}
library(targets)
library(DT)
```

```{r git_check, echo=FALSE}
{
s = function(cmd) suppressWarnings(system(cmd,
    intern = TRUE, ignore.stderr = TRUE))
commit = substr(s('git rev-parse HEAD'), 1, 8)
uncommitted = ''
if (!length(commit))
   commit = 'unknown'
else if(length(s('git diff-index HEAD --'))>0)
   uncommitted = 'with uncommitted changes'
}
```

Git commit: `r commit` `r uncommitted`

Rendered: `r Sys.time()`

### 5 fold CV summary statistics
```{r table_cv_results, echo=FALSE}
tar_load(cv_summary_tables)
DT::datatable(cv_summary_tables$stat,
              rownames = FALSE,
              fillContainer = FALSE,
              autoHideNavigation = TRUE,
              options = list(pageLength = 50,
                             autoWidth = TRUE))
```

### AERONET & MCD19 observation time difference distribution, in seconds
```{r table_difftime_distribution, echo=FALSE}
DT::datatable(cv_summary_tables$difftimes,
              rownames = FALSE,
              fillContainer = FALSE,
              autoHideNavigation = TRUE,
              options = list(pageLength = 50,
                             autoWidth = TRUE))
```

### Raw console print of above tables:
```{r dt_raw, echo=FALSE}
options(max.print = 1000)
cv_summary_tables
```
